// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_JsnDMkn6vdO05DJLK6JlxLIG0txpAkM',
    appId: '1:442709428745:web:033b15f5676fac7ab386d8',
    messagingSenderId: '442709428745',
    projectId: 'buscar-app01',
    authDomain: 'buscar-app01.firebaseapp.com',
    storageBucket: 'buscar-app01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr-apOr6oX70wcq7Nmvdu73n68r0aPn2U',
    appId: '1:442709428745:android:9ca30901f231f813b386d8',
    messagingSenderId: '442709428745',
    projectId: 'buscar-app01',
    storageBucket: 'buscar-app01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYIE03DjRkS8etZVpBnxQuwBzcWRQDOpQ',
    appId: '1:442709428745:ios:24b0d3618c298dc4b386d8',
    messagingSenderId: '442709428745',
    projectId: 'buscar-app01',
    storageBucket: 'buscar-app01.firebasestorage.app',
    iosBundleId: 'com.example.cardApp',
  );
}
